SELECT * FROM customers limit 

--Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender,
    SUM(purchase_amount) AS revenue
FROM customers
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customers
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
        SELECT AVG(purchase_amount) 
        FROM customers
    );

-- Q3. Top 5 products with the highest average review rating
SELECT TOP 5 
    item_purchased,
    ROUND(AVG(CAST(review_rating AS FLOAT)), 2) AS Average_Product_Rating
FROM customers
GROUP BY item_purchased
ORDER BY AVG(CAST(review_rating AS FLOAT)) DESC;

-- Q4. Compare average purchase amounts between Standard and Express shipping
SELECT shipping_type, 
       ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customers
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customers
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q6. Top 5 products with the highest discount usage rate
SELECT TOP 5
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC;

-- Q7. Customer segmentation based on previous purchases
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customers
)
SELECT customer_segment,
       COUNT(*) AS Number_of_Customers
FROM customer_type
GROUP BY customer_segment;

-- Q8. Top 3 most purchased products within each category
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9. Repeat buyers who subscribed vs not subscribed
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. Total revenue contributed by each age group
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;
